
if typeof window.GS is 'undefined'
  window.GS = {}
  
GS.EVENTS = GS.EVENTS or {}

GS.EVENTS.RESIZE_BEGIN        = 'GS_RESIZE_BEGIN'

GS.EVENTS.CHILD_RESIZE_BEGIN  = 'GS_CHILD_RESIZE_BEGIN'
GS.EVENTS.CHILD_RESIZE        = 'GS_CHILD_RESIZE'
GS.EVENTS.CHILD_RESIZE_FINISH = 'GS_CHILD_RESIZE_FINISH'
GS.EVENTS.CHILD_MAKE_RESIZE   = 'GS_CHILD_MAKE_RESIZE'

GS.EVENTS.CHILD_REMOVE        = 'GS_CHILD_REMOVE'

GS.EVENTS.UNREGISTER          = 'GS_UNREGISTER'

GS.EVENTS.PANELS_CHANGE       = 'GS_PANELS_CHANGE'

GS.EVENTS.HAS_BEEN_RESIZED    = 'GS_HAS_BEEN_RESIZED'

GS.EVENTS.RESIZER_SUBSCRIBE   = 'GS_RESIZER_SUBSCRIBE'

