
if typeof window.GS is 'undefined'
  window.GS = {}
  
GS.EVENTS = GS.EVENTS or {}

GS.EVENTS.RESIZE_BEGIN        = 'RESIZE_BEGIN'

GS.EVENTS.CHILD_RESIZE_BEGIN  = 'CHILD_RESIZE_BEGIN'
GS.EVENTS.CHILD_RESIZE        = 'CHILD_RESIZE'
GS.EVENTS.CHILD_RESIZE_FINISH = 'CHILD_RESIZE_FINISH'